import React from 'react';
import { createClient } from '../../../lib/supabase/server';

// Force dynamic rendering so data is fetched on each request
export const dynamic = 'force-dynamic';

// --- TYPES ---
type ShareData = {
  slug: string;
  title: string | null;
  dna: any;
  created_at: string;
};

// --- DATA FETCHING ---
async function fetchShares() {
  const supabase = createClient({ useServiceRole: true });
  const { data, error } = await supabase
    .from('liveheart_shares')
    .select('slug, title, dna, created_at')
    .order('created_at', { ascending: false })
    .limit(5000);

  if (error) throw error;
  return (data || []) as ShareData[];
}

// --- COMPONENTS ---

// Colorful Stat Bar
const FunStatBar = ({ title, data, colorClass }: { title: string, data: Record<string, number>, colorClass: string }) => {
  const sorted = Object.entries(data).sort((a, b) => b[1] - a[1]).slice(0, 6); // Top 6 only
  const maxVal = sorted[0]?.[1] || 1;

  return (
    <div className="bg-zinc-900/50 rounded-2xl p-6 backdrop-blur-sm border border-white/5">
      <h3 className="text-sm font-bold text-white/90 mb-6 flex items-center gap-2">
        {title}
      </h3>
      <div className="space-y-4">
        {sorted.map(([label, count]) => (
          <div key={label} className="relative">
            <div className="flex justify-between text-xs text-gray-400 mb-1 z-10 relative font-medium">
              <span>{label}</span>
              <span>{count}</span>
            </div>
            <div className="h-3 w-full bg-white/5 rounded-full overflow-hidden">
              <div 
                className={`h-full rounded-full ${colorClass}`}
                style={{ width: `${(count / maxVal) * 100}%` }}
              />
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// Big Number Card
const BigNumber = ({ label, value, icon }: { label: string, value: string | number, icon: string }) => (
  <div className="bg-zinc-900/50 p-6 rounded-2xl border border-white/5 flex flex-col justify-center items-center text-center hover:bg-zinc-800/50 transition-colors cursor-default">
    <div className="text-2xl mb-2">{icon}</div>
    <div className="text-4xl font-bold text-white mb-1 tracking-tight">{value}</div>
    <div className="text-xs text-gray-400 font-medium uppercase tracking-wider">{label}</div>
  </div>
);

// --- PAGE ---
export default async function StatisticsPage({ searchParams }: { searchParams?: { debug?: string } }) {
  let rows: ShareData[] = [];
  try {
    rows = await fetchShares();
  } catch (err) {
    console.error('Failed to load shares', err);
  }

  const total = rows.length;
  
  const stats = {
    structure: {} as Record<string, number>,
    physics: {} as Record<string, number>,
    scale: {} as Record<string, number>,
    palettes: {} as Record<string, number>,
  };

  rows.forEach((r) => {
    const dna = r.dna || {};
    // Fallbacks with nicer names
    const s = (dna.structure || 'Mystery').toString();
    const p = (dna.physics || 'Unknown').toString();
    const sc = (dna.scaleMode || 'Standard').toString();
    const pal = (dna.name ? dna.name.split(' ')[0] : 'Custom').toString();

    stats.structure[s] = (stats.structure[s] || 0) + 1;
    stats.physics[p] = (stats.physics[p] || 0) + 1;
    stats.scale[sc] = (stats.scale[sc] || 0) + 1;
    stats.palettes[pal] = (stats.palettes[pal] || 0) + 1;
  });

  const top = rows.slice(0, 32); 

  const showDebug = (searchParams?.debug === '1') || process.env.NODE_ENV === 'development';

  return (
    <div className="min-h-screen bg-black text-white selection:bg-pink-500 selection:text-white pb-20">
      
      {/* HEADER */}
      <div className="relative bg-gradient-to-b from-zinc-900 to-black pt-20 pb-16 px-6">
        <div className="max-w-7xl mx-auto text-center">
          <h1 className="text-5xl md:text-7xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 mb-6 pb-2">
            Global Gallery
          </h1>
          <p className="text-lg md:text-xl text-gray-400 max-w-2xl mx-auto font-light leading-relaxed">
            Thousands of unique hearts generated by human movement. <br/>
            From chaotic scribbles to smooth flows — everything is preserved here.
          </p>
        </div>
      </div>

      <main className="max-w-7xl mx-auto px-6 -mt-8">
        
        {/* BIG NUMBERS */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-12">
          <BigNumber icon="❤️" label="Total Hearts" value={total} />
          <BigNumber icon="🎨" label="Unique Colors" value={Object.keys(stats.palettes).length} />
          <BigNumber icon="✨" label="Shapes" value={Object.keys(stats.structure).length} />
          <BigNumber icon="⚡️" label="Moods" value={Object.keys(stats.physics).length} />
        </div>

        {showDebug && (
          <div className="mb-8 p-4 bg-zinc-800/60 rounded-lg border border-white/5 text-xs">
            <div className="font-semibold mb-2">Debug: query results</div>
            <pre className="whitespace-pre-wrap overflow-x-auto">{JSON.stringify({
              total,
              sample: rows.slice(0, 16).map(r => ({ slug: r.slug, created_at: r.created_at })),
              supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || 'not-set'
            }, null, 2)}</pre>
          </div>
        )}

        {/* CHARTS */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-20">
          <FunStatBar 
            title="Most Popular Shapes" 
            data={stats.structure} 
            colorClass="bg-gradient-to-r from-blue-400 to-cyan-300"
          />
          <FunStatBar 
            title="Common Vibes (Physics)" 
            data={stats.physics} 
            colorClass="bg-gradient-to-r from-purple-400 to-pink-300"
          />
          <FunStatBar 
            title="Scale Preferences" 
            data={stats.scale} 
            colorClass="bg-gradient-to-r from-amber-400 to-orange-300"
          />
        </div>

        {/* GALLERY GRID */}
        <div className="mb-8 flex items-center justify-between">
          <h2 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-500">
            Fresh Arrivals
          </h2>
          <a href="/liveheart" className="text-sm font-medium text-pink-400 hover:text-pink-300 transition-colors">
            Create yours →
          </a>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-6">
          {top.map((r) => {
            const palette = (r.dna?.palette && Array.isArray(r.dna.palette)) 
              ? r.dna.palette 
              : ['#333', '#000'];
            
            // Generate a nice gradient based on the heart's DNA
            const grad = `linear-gradient(45deg, hsla(${palette[0]}, 1) 0%, hsla(${palette[1]||palette[0]}, 1) 100%)`;

            return (
              <a 
                key={r.slug} 
                href={`/liveheart/${r.slug}`} 
                className="group relative bg-zinc-900 rounded-2xl overflow-hidden hover:-translate-y-1 transition-all duration-300 shadow-lg hover:shadow-pink-500/20"
              >
                {/* Visual Preview */}
                <div className="aspect-square p-6 flex items-center justify-center bg-black relative">
                    <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20"></div>
                    <div 
                      className="w-16 h-16 rounded-full blur-xl opacity-60 group-hover:opacity-100 group-hover:scale-125 transition-all duration-500"
                      style={{ background: grad }}
                    ></div>
                    <div 
                      className="w-12 h-12 rounded-full relative z-10"
                      style={{ background: grad, boxShadow: `0 0 20px hsla(${palette[0]}, 0.5)` }}
                    ></div>
                </div>
                
                {/* Caption */}
                <div className="p-4 bg-zinc-900 border-t border-white/5">
                  <h4 className="text-white font-bold text-sm truncate mb-1">
                    {r.title || r.dna?.name || "Untitled"}
                  </h4>
                  <div className="flex justify-between items-center text-[10px] text-gray-500 font-medium uppercase tracking-wide">
                    <span>{r.dna?.structure || "Shape"}</span>
                    <span>{new Date(r.created_at).toLocaleDateString()}</span>
                  </div>
                </div>
              </a>
            );
          })}
        </div>

      </main>
    </div>
  );
}