import Link from "next/link";
import { SubmitButton } from "./submit-button"; // Создадим ниже компонент кнопки
import { submitInquiry } from "./actions";

export const metadata = {
  title: 'The Merkurov Doctrine — Research',
  description: 'A forensic study: The Digital Decay — a chronicle and analysis (2010–2025).',
  openGraph: {
    title: 'The Merkurov Doctrine — Research',
    description: 'A forensic study: The Digital Decay — a chronicle and analysis (2010–2025).',
    url: 'https://www.merkurov.love/research',
    images: [
      {
        url: 'https://txvkqcitalfbjytmnawq.supabase.co/storage/v1/object/public/media/logo.png',
        width: 1200,
        height: 630,
        alt: 'Merkurov.love',
      },
    ],
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'The Merkurov Doctrine — Research',
    description: 'A forensic study: The Digital Decay — a chronicle and analysis (2010–2025).',
  },
};

export default function ResearchPage() {
  const pdfUrl = "https://txvkqcitalfbjytmnawq.supabase.co/storage/v1/object/public/media/The%20Merkurov%20Timeline%20of%20Digital%20Decay%20A%20Manifesto%20of%20Unheeded.pdf";

  return (
    <main className="min-h-screen bg-[#0a0a0a] text-zinc-300 font-sans selection:bg-red-900 selection:text-white">
      {/* NAV */}
      <nav className="border-b border-zinc-900 p-6 flex justify-between items-center text-xs tracking-widest font-mono text-zinc-500">
        <Link href="/" className="hover:text-white transition">MERKUROV.LOVE</Link>
        <span>RESEARCH / CS-001</span>
      </nav>

      <div className="max-w-4xl mx-auto px-6 py-20">
        
        {/* HEADER */}
        <header className="mb-24 border-l-2 border-red-700 pl-8">
          <h1 className="text-4xl md:text-6xl font-serif font-bold text-zinc-100 mb-4 leading-tight">
            The Digital Decay:<br />
            <span className="text-zinc-500">A Chronicle of Voluntary Submission.</span>
          </h1>
          <div className="flex flex-col md:flex-row gap-6 text-sm font-mono text-zinc-400 mt-8">
            <span>// ARCHIVE: 2010–2025</span>
            <span>// STATUS: IRREVERSIBLE</span>
            <span className="text-red-500">// AUTHOR: ANTON MERKUROV</span>
          </div>
        </header>

        {/* ABSTRACT */}
        <section className="mb-24 grid md:grid-cols-3 gap-12">
          <div className="md:col-span-1">
            <h3 className="text-xs font-mono text-zinc-500 mb-4 tracking-widest uppercase">Abstract</h3>
            <p className="text-zinc-400 text-sm leading-relaxed">
              Generated by Google Deep Research AI based on 15 years of public commentary in BBC, Washington Post, Novaya Gazeta, and Al Jazeera. A forensic analysis of foresight.
            </p>
          </div>
          <div className="md:col-span-2">
            <p className="text-lg md:text-xl font-serif leading-relaxed text-zinc-200">
              The internet was not killed by the state. It was surrendered by the user. 
              This document traces the evolution of the "Digital Iron Curtain" from a technical impossibility (2012) to a psychological reality (2025).
            </p>
          </div>
        </section>

        {/* TIMELINE */}
        <section className="mb-24">
          <h3 className="text-xs font-mono text-zinc-500 mb-8 tracking-widest uppercase border-b border-zinc-900 pb-2">The Timeline of Warnings</h3>
          
          <div className="space-y-12 border-l border-zinc-800 ml-2 pl-8 relative">
            
            {/* ITEM 1 */}
            <div className="relative">
              <span className="absolute -left-[37px] top-1 h-4 w-4 rounded-full bg-zinc-900 border border-zinc-700"></span>
              <div className="font-mono text-red-500 text-sm mb-1">2012 — THE ILLUSION</div>
              <h4 className="text-xl font-bold text-zinc-100 mb-2">"Shooting Themselves in the Foot"</h4>
              <p className="text-zinc-400 italic">Prediction: Banning IPs will destroy the economy before it destroys dissent.</p>
              <div className="mt-2 text-xs text-zinc-600 font-mono">Source: BBC Interview</div>
            </div>

            {/* ITEM 2 */}
            <div className="relative">
              <span className="absolute -left-[37px] top-1 h-4 w-4 rounded-full bg-zinc-900 border border-zinc-700"></span>
              <div className="font-mono text-red-500 text-sm mb-1">2018 — THE RESISTANCE</div>
              <h4 className="text-xl font-bold text-zinc-100 mb-2">"The Digital Migration"</h4>
              <p className="text-zinc-400 italic">Prediction: The state cannot win a math war (Encryption), but they will win a physical war (Fear).</p>
              <div className="mt-2 text-xs text-zinc-600 font-mono">Source: Al Jazeera / DW</div>
            </div>

            {/* ITEM 3 */}
            <div className="relative">
              <span className="absolute -left-[37px] top-1 h-4 w-4 rounded-full bg-red-900 border border-red-500 shadow-[0_0_15px_rgba(220,38,38,0.5)]"></span>
              <div className="font-mono text-red-500 text-sm mb-1">2025 — THE COLLAR</div>
              <h4 className="text-xl font-bold text-zinc-100 mb-2">"Voluntary Submission"</h4>
              <p className="text-zinc-400 italic">Verdict: The infrastructure of control is now internal. We register ourselves.</p>
              <div className="mt-2 text-xs text-zinc-600 font-mono">Source: The Merkurov Doctrine</div>
            </div>

          </div>
        </section>

        {/* DOWNLOAD */}
        <section className="mb-24 p-8 border border-zinc-800 bg-zinc-900/30 flex flex-col md:flex-row items-center justify-between gap-6">
          <div>
            <h3 className="text-lg font-bold text-white">Full Dossier (PDF)</h3>
            <p className="text-sm text-zinc-500 font-mono mt-1">12 Pages • Academic Analysis • 2.4 MB</p>
          </div>
          <a 
            href={pdfUrl}
            target="_blank"
            className="px-6 py-3 bg-zinc-100 text-black font-mono text-sm uppercase tracking-wider hover:bg-zinc-300 transition"
          >
            Download Artifact
          </a>
        </section>

        {/* CONTACT FORM */}
        <section className="border-t border-zinc-900 pt-12">
          <div className="grid md:grid-cols-2 gap-12">
            <div>
              <h3 className="text-2xl font-serif text-white mb-4">Academic Inquiry</h3>
              <p className="text-zinc-400 text-sm mb-6">
                Available for university lectures, think-tank briefings, and institutional review.
                <br/><br/>
                Request access to the Private Office.
              </p>
            </div>

            <form action={submitInquiry} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <input 
                  name="name" 
                  placeholder="Name" 
                  className="bg-zinc-900 border border-zinc-800 p-3 text-sm text-white focus:outline-none focus:border-red-900 transition"
                  required
                />
                <input 
                  name="org" 
                  placeholder="Institution / Org" 
                  className="bg-zinc-900 border border-zinc-800 p-3 text-sm text-white focus:outline-none focus:border-red-900 transition"
                />
              </div>
              <input 
                name="email" 
                type="email"
                placeholder="Institutional Email" 
                className="w-full bg-zinc-900 border border-zinc-800 p-3 text-sm text-white focus:outline-none focus:border-red-900 transition"
                required
              />
              <SubmitButton />
            </form>
          </div>
        </section>

      </div>
    </main>
  );
}